Edited the groomer dashboard feature to allow groomers to upload and …
Lambda-School-Labs/express-groomer-c-fe pull request #3
Opened 2021-03-03 02:21 UTC by broph123

…view their license.

## Description ##

The feature I updated relates to Groomer in their dashboard being able to upload their grooming license allowing them to operate. This aspect of the groomer dashboard is important because groomers need to be able to manage their licensing paperwork in order to operate their business. Customers also feel safer knowing that their groomer is licensed and can see the uploaded paperwork in their customer dashboard. 

Before I made changes, the groomer could upload an image and only the file name would render. After I made changes, I added to the functionality allowing not only the file name to render but also a smaller version of the document. I also added the ability for groomers to click on the picture to enlarge it. 

There is still some work to be done. The backend and this feature update are not connected. Also the image uploader only accepts .jpg and .pngs right now. I tried uploading a PDF and it wouldn't render on screen. 

user story link: https://trello.com/c/J63WiV48/2-as-a-groomer-i-can-add-my-groomer-license-number-and-upload-a-copy-of-my-license

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ X] This is part of a feature.

## Organization ##

- [X ] Have you linked this pull request to a Trello card?
- [ ] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 
## Review ##

- [X ] Is this a work in progress?
- [ ] Is this ready to be reviewed?
- [ X] Have you added two reviewers to this pull request?

2021-03-16 02:23 UTC, cearc-sara requested changes
Please review the comments I left throughout the code, and make the appropriate changes.

2021-03-16 02:23 UTC, cearc-sara commented on src/components/common/FileUpload.js
> +// import axios from 'axios';
why is this commented out? Does it need to be there? If so please leave a comment next to it as to why its commented out.

2021-03-16 02:23 UTC, cearc-sara commented on src/components/common/FileUpload.js
> +  // const getAuthHeader = authState => {
same with all the code in this file, if it needs to be commented out, leave a comment next to them as to why, if they do not need to be there then just delete them.

2021-03-17 22:35 UTC, cearc-sara requested changes
Just review the comment I left and let me know when you have changed it.

2021-03-17 22:35 UTC, cearc-sara commented on .env.sample
> -REACT_APP_CLIENT_ID=example
yeah this is the example that needs to be in the github, there isn't anything in there that is specific to our project. So just add that back and then push again and you should be good to go.

2021-03-30 00:06 UTC, cearc-sara approved these changes

2021-03-30 00:09 UTC, vishalicious213 approved these changes
The groomer license components look fine to me. You're good to go!

2021-03-30 00:10 UTC, merged